### ISSUE TITLE
您导出的yolov5s.onnx的推理结果和原版python差别很大

### ISSUE THREAD

**Issue by goodtogood** [hpc203/yolov5-dnn-cpp-python-v2#2]
您导出的yolov5s.onnx的推理结果和原版python差别很大
会是什么原因造成的呢
谢谢

**Comment by hpc203** [comment]
> 您导出的yolov5s.onnx的推理结果和原版python差别很大
> 会是什么原因造成的呢
> 谢谢



> 您导出的yolov5s.onnx的推理结果和原版python差别很大
> 会是什么原因造成的呢
> 谢谢

**Comment by hpc203** [comment]
> 您导出的yolov5s.onnx的推理结果和原版python差别很大
> 会是什么原因造成的呢
> 谢谢

你说的原版python是指ultralytics的yolov5吗？ultralytics的yolov5仓库代码几乎每天都在更新，而我这个opencv代码是1月份编写的，很有可能ultralytics的yolov5网络结构已经发生了变化，还有就是在ultralytics的yolov5的测试程序里，输入图片的预处理resize并不是resize到固定的正方形尺寸640x640的，而是保持高宽比的长方形。而在我的opencv代码里，都是resize到640x640的
